-- Adicionar campos para NFe e estoque na tabela produtos
ALTER TABLE public.produtos
ADD COLUMN IF NOT EXISTS codigo_barras VARCHAR(20),
ADD COLUMN IF NOT EXISTS grupo VARCHAR(50),
ADD COLUMN IF NOT EXISTS artigo_nfe VARCHAR(200),
ADD COLUMN IF NOT EXISTS preco_prazo NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS estoque_maximo NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS tempo_maximo INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS qtd_venda NUMERIC DEFAULT 1,
ADD COLUMN IF NOT EXISTS cod_fornecedor VARCHAR(50),
ADD COLUMN IF NOT EXISTS peso_saco NUMERIC DEFAULT 60,
ADD COLUMN IF NOT EXISTS produto_residuo_id UUID REFERENCES public.produtos(id),
ADD COLUMN IF NOT EXISTS ncm VARCHAR(10),
ADD COLUMN IF NOT EXISTS cst_pis VARCHAR(3),
ADD COLUMN IF NOT EXISTS cst_cofins VARCHAR(3),
ADD COLUMN IF NOT EXISTS cst_icms VARCHAR(3),
ADD COLUMN IF NOT EXISTS cst_ipi VARCHAR(3),
ADD COLUMN IF NOT EXISTS natureza_receita VARCHAR(10),
ADD COLUMN IF NOT EXISTS observacao_tributaria TEXT;